spring:
  application:
    name: aiservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/fitnessActivity

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  queue:
    name: ai.queue
  exchange:
    name: ai.exchange
  routing:
    key: ai.routing

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}